### PR TITLE
Contact

### PR DESCRIPTION
**Pull request by Fleury14**
@pakawaka1 Finished contact portion. Let me know if you have any questions.

### CODE REVIEW

**Comment by pakawaka1** [comment]
T.J.
I saw your code and noticed you were able to get padding for the contact form box.  I tried to do that today but wasn't to get it.  

Do you know how to view the page itself through github?

I will send you my latest updates to the restaurante page as well,.

David

**Comment by pakawaka1** [comment]
T.J.

Please take a look at my gh-pages branch.  

Thanks,

David

**Comment by Fleury14** [comment]
@pakawaka1 I got padding on the contact form by targeting the `<form>` element and adding "padding: 10px;". in your case, since you gave your form element the class "info", you could add to the current css for .info and add the padding there.

**Comment by pakawaka1** [comment]
J.R.,

Thank you for taking a look at my code and the suggestions.  

I took at look at your code and it looks good.  Go ahead and merge if you haven't yet.

David

**Pull request merged**
